on: push

jobs:
  jinja:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir /tmp/modules && pip3 install --root /tmp/modules/ jinja2-cli
    - run: jinja2
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          Write-Host -Object '::add-mask::world'
          Write-Host -Object unmasked
          Write-Host -Object 'Hello world'
          Write-Host -Object world123
  bunchaguids:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object '::group::1'
        1..100 | % {
          (New-Guid).Guid
          if (($PSItem % 5) -eq 0) { 
            Write-Host -Object '::endgroup::'
            Write-Host -Object ('::group::Group {0}' -f ($PSItem+1))
          }
        }
        Write-Host -Object '::endgroup::'
