on: push

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/caddyserver/caddy/releases/download/v2.4.6/caddy_2.4.6_linux_amd64.tar.gz
    - run: tar xzf caddy_2.4.6_linux_amd64.tar.gz
    - run: mkdir /tmp/caddy && cp caddy /tmp/caddy/
    - run: echo /tmp/caddy/ >> $GITHUB_PATH
    - id: caddyversion
      run: caddy version
#   jinja:
#     runs-on: ubuntu-latest
#     steps:
#     - run: mkdir /tmp/modules && pip3 install --root /tmp/modules/ jinja2-cli
#     - run: echo '/tmp/modules/home/runner/.local/bin/' >> $GITHUB_PATH
#     - run: ls -R /tmp/modules
#     - run: jinja2
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          Write-Host -Object '::add-mask::world'
          Write-Host -Object unmasked
          Write-Host -Object 'Hello world'
          Write-Host -Object world123
  bunchaguids:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object '::group::1'
        1..100 | % {
          (New-Guid).Guid
          if (($PSItem % 5) -eq 0) { 
            Write-Host -Object '::endgroup::'
            Write-Host -Object ('::group::Group {0}' -f ($PSItem+1))
          }
        }
        Write-Host -Object '::endgroup::'
