on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          Write-Host -Object '::add-mask::world'
          Write-Host -Object unmasked
          Write-Host -Object 'Hello world'
          Write-Host -Object world123
